# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCitationCFF: false
AddCodeOfConduct: false
AddCompatHelperCI: true
AddContributionDocs: false
AddCopierCI: false
AddDependabot: true
AddDocs: true
AddDocsCI: true
AddFormatterAndLinterConfigFiles: true
AddGitHubPRTemplate: true
AddGitHubTemplates: true
AddLintCI: false
AddLychee: false
AddMacToCI: false
AddPrecommit: true
AddTagBotCI: false
AddTestCI: true
AddWinToCI: false
Authors: hzxiaxz <hzxiaxz@gmail.com>
AutoIncludeTests: true
CheckExplicitImports: false
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinCIVersion: lts
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: hzxiaxz
MarkdownIndentation: 2
PackageName: KagomeDSL
PackageOwner: hz-xiaxz
PackageUUID: d7336a9d-6a7f-533d-babd-3df937e6f042
RunJuliaNightlyOnCI: false
StrategyConfirmIncluded: true
StrategyLevel: 0
StrategyReviewExcluded: true
UseCirrusCI: false
_commit: v0.16.2
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
