exclude = [
  "@ref",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://doi.org/FIXME$",
  "^https://hz-xiaxz.github.io/KagomeDSL.jl/stable$",
  "^https://hz-xiaxz.github.io/KagomeDSL.jl/dev$",
  "zenodo.org/badge/DOI/FIXME$"
]

exclude_path = [
  "docs/build"
]
